import type { AttachmentRecord } from "../schemas";

const EDITORIAL = {
  dataStatus: "unverified" as const,
  sourceName: "ClutchLab editorial baseline (pending verification)",
  sourceUrl: null,
  sourceDate: "2026-07-21",
};

/**
 * Attachment catalog with QUALITATIVE effects only (spec §5.5): direction and
 * magnitude, never invented percentages. Numeric effect data arrives via the
 * verified-measurement workflow.
 */
export const ATTACHMENTS: AttachmentRecord[] = [
  {
    ...EDITORIAL,
    slug: "compensator_ar",
    name: "Compensator (AR, DMR, S12K)",
    slot: "muzzle",
    compatibleClasses: ["ar", "dmr", "shotgun"],
    description: "The default spray muzzle: trades sound signature for recoil reduction.",
    effects: [
      { key: "vertical_recoil", direction: "improves", magnitude: "moderate", note: null },
      { key: "horizontal_recoil", direction: "improves", magnitude: "moderate", note: null },
      { key: "sound_signature", direction: "worsens", magnitude: "minor", note: "Louder/more visible than suppressed setups." },
    ],
  },
  {
    ...EDITORIAL,
    slug: "flash_hider_ar",
    name: "Flash Hider (AR, DMR, S12K)",
    slot: "muzzle",
    compatibleClasses: ["ar", "dmr", "shotgun"],
    description: "Hides muzzle flash with a modest recoil benefit.",
    effects: [
      { key: "muzzle_flash", direction: "improves", magnitude: "major", note: null },
      { key: "vertical_recoil", direction: "improves", magnitude: "minor", note: null },
    ],
  },
  {
    ...EDITORIAL,
    slug: "suppressor_ar",
    name: "Suppressor (AR, DMR, S12K)",
    slot: "muzzle",
    compatibleClasses: ["ar", "dmr", "shotgun"],
    description: "Silence over stability: positional advantage, no recoil help.",
    effects: [
      { key: "sound_signature", direction: "improves", magnitude: "major", note: null },
      { key: "recoil", direction: "none", magnitude: "unknown", note: "No direct recoil reduction." },
    ],
  },
  {
    ...EDITORIAL,
    slug: "compensator_smg",
    name: "Compensator (SMG)",
    slot: "muzzle",
    compatibleClasses: ["smg"],
    description: "SMG spray stabilizer for sustained close fights.",
    effects: [
      { key: "vertical_recoil", direction: "improves", magnitude: "moderate", note: null },
      { key: "horizontal_recoil", direction: "improves", magnitude: "moderate", note: null },
    ],
  },
  {
    ...EDITORIAL,
    slug: "suppressor_smg",
    name: "Suppressor (SMG)",
    slot: "muzzle",
    compatibleClasses: ["smg"],
    description: "Quiet compound clears; pairs with UMP45 for stealth play.",
    effects: [{ key: "sound_signature", direction: "improves", magnitude: "major", note: null }],
  },
  {
    ...EDITORIAL,
    slug: "suppressor_sr",
    name: "Suppressor (SR)",
    slot: "muzzle",
    compatibleClasses: ["sr", "dmr"],
    description: "Removes the shot-direction giveaway on bolt actions and DMRs.",
    effects: [{ key: "sound_signature", direction: "improves", magnitude: "major", note: null }],
  },
  {
    ...EDITORIAL,
    slug: "choke",
    name: "Choke",
    slot: "muzzle",
    compatibleClasses: ["shotgun"],
    description: "Tightens shotgun pellet spread for longer effective range.",
    effects: [{ key: "pellet_spread", direction: "improves", magnitude: "moderate", note: null }],
  },
  {
    ...EDITORIAL,
    slug: "duckbill",
    name: "Duckbill",
    slot: "muzzle",
    compatibleClasses: ["shotgun"],
    description: "Widens spread horizontally, narrows vertically — strafing targets.",
    effects: [
      { key: "pellet_spread", direction: "mixed", magnitude: "moderate", note: "Horizontal wider, vertical tighter." },
    ],
  },
  {
    ...EDITORIAL,
    slug: "vertical_grip",
    name: "Vertical Foregrip",
    slot: "grip",
    compatibleClasses: ["ar", "smg", "dmr", "lmg"],
    description: "The vertical-recoil specialist.",
    effects: [
      { key: "vertical_recoil", direction: "improves", magnitude: "moderate", note: null },
      { key: "horizontal_recoil", direction: "none", magnitude: "unknown", note: "Little help with side-to-side drift." },
    ],
  },
  {
    ...EDITORIAL,
    slug: "angled_grip",
    name: "Angled Foregrip",
    slot: "grip",
    compatibleClasses: ["ar", "smg", "dmr"],
    description: "Faster ADS with horizontal-recoil help.",
    effects: [
      { key: "ads_speed", direction: "improves", magnitude: "moderate", note: null },
      { key: "horizontal_recoil", direction: "improves", magnitude: "minor", note: null },
    ],
  },
  {
    ...EDITORIAL,
    slug: "half_grip",
    name: "Half Grip",
    slot: "grip",
    compatibleClasses: ["ar", "smg", "dmr"],
    description: "Overall recoil and recovery boost at the cost of stability while moving.",
    effects: [
      { key: "recoil_recovery", direction: "improves", magnitude: "moderate", note: null },
      { key: "vertical_recoil", direction: "improves", magnitude: "minor", note: null },
      { key: "weapon_sway", direction: "worsens", magnitude: "minor", note: null },
    ],
  },
  {
    ...EDITORIAL,
    slug: "thumb_grip",
    name: "Thumb Grip",
    slot: "grip",
    compatibleClasses: ["ar", "smg", "dmr"],
    description: "Fastest scope-in among grips; first-shot oriented.",
    effects: [
      { key: "ads_speed", direction: "improves", magnitude: "major", note: null },
      { key: "vertical_recoil", direction: "worsens", magnitude: "minor", note: "Slightly harder sustained spray." },
    ],
  },
  {
    ...EDITORIAL,
    slug: "light_grip",
    name: "Light Grip",
    slot: "grip",
    compatibleClasses: ["ar", "smg", "dmr"],
    description: "Recoil-recovery focus; niche tap-fire choice.",
    effects: [
      { key: "recoil_recovery", direction: "improves", magnitude: "major", note: null },
      { key: "sustained_stability", direction: "worsens", magnitude: "minor", note: null },
    ],
  },
  {
    ...EDITORIAL,
    slug: "laser_sight",
    name: "Laser Sight",
    slot: "grip",
    compatibleClasses: ["ar", "smg", "pistol"],
    description: "Tightens hip-fire spread for no-ADS fights.",
    effects: [{ key: "hipfire_spread", direction: "improves", magnitude: "moderate", note: null }],
  },
  {
    ...EDITORIAL,
    slug: "red_dot",
    name: "Red Dot Sight",
    slot: "scope",
    compatibleClasses: ["ar", "smg", "dmr", "sr", "lmg", "shotgun", "pistol"],
    description: "Clean 1× reference sight for close-range tracking.",
    effects: [{ key: "sight_picture", direction: "improves", magnitude: "moderate", note: null }],
  },
  {
    ...EDITORIAL,
    slug: "holographic",
    name: "Holographic Sight",
    slot: "scope",
    compatibleClasses: ["ar", "smg", "dmr", "sr", "lmg", "shotgun"],
    description: "1× with a boxier reticle; preference-driven alternative to the red dot.",
    effects: [{ key: "sight_picture", direction: "improves", magnitude: "moderate", note: null }],
  },
  {
    ...EDITORIAL,
    slug: "scope_2x",
    name: "2× Aimpoint Scope",
    slot: "scope",
    compatibleClasses: ["ar", "smg", "dmr", "sr", "lmg"],
    description: "Short-mid magnification with easy spray control.",
    effects: [{ key: "magnification", direction: "improves", magnitude: "minor", note: null }],
  },
  {
    ...EDITORIAL,
    slug: "scope_3x",
    name: "3× Backlit Scope",
    slot: "scope",
    compatibleClasses: ["ar", "smg", "dmr", "sr", "lmg"],
    description: "The mid-range spray standard for most AR players.",
    effects: [{ key: "magnification", direction: "improves", magnitude: "moderate", note: null }],
  },
  {
    ...EDITORIAL,
    slug: "scope_4x",
    name: "4× ACOG Scope",
    slot: "scope",
    compatibleClasses: ["ar", "smg", "dmr", "sr", "lmg"],
    description: "Long-mid scope; sprayable only with strong recoil control.",
    effects: [{ key: "magnification", direction: "improves", magnitude: "moderate", note: null }],
  },
  {
    ...EDITORIAL,
    slug: "scope_6x",
    name: "6× Scope",
    slot: "scope",
    compatibleClasses: ["ar", "dmr", "sr", "lmg"],
    description: "Variable 3–6×: DMR glass that doubles as a sprayable 3× when zoomed out.",
    effects: [{ key: "magnification", direction: "improves", magnitude: "major", note: null }],
  },
  {
    ...EDITORIAL,
    slug: "scope_8x",
    name: "8× CQBSS Scope",
    slot: "scope",
    compatibleClasses: ["dmr", "sr"],
    description: "Maximum magnification; bolt-action and DMR territory only.",
    effects: [{ key: "magnification", direction: "improves", magnitude: "major", note: null }],
  },
  {
    ...EDITORIAL,
    slug: "canted_sight",
    name: "Canted Sight",
    slot: "canted",
    compatibleClasses: ["ar", "smg", "dmr", "sr", "lmg"],
    description: "Secondary 1× on a side rail — instant close-range answer on scoped rifles.",
    effects: [{ key: "sight_flexibility", direction: "improves", magnitude: "moderate", note: null }],
  },
  {
    ...EDITORIAL,
    slug: "quickdraw_mag",
    name: "Quickdraw Mag",
    slot: "magazine",
    compatibleClasses: ["ar", "smg", "dmr", "sr", "pistol"],
    description: "Faster reloads, standard capacity.",
    effects: [{ key: "reload_speed", direction: "improves", magnitude: "moderate", note: null }],
  },
  {
    ...EDITORIAL,
    slug: "extended_mag",
    name: "Extended Mag",
    slot: "magazine",
    compatibleClasses: ["ar", "smg", "dmr", "sr", "pistol"],
    description: "More rounds per magazine; the Vector's mandatory upgrade.",
    effects: [{ key: "magazine_capacity", direction: "improves", magnitude: "major", note: null }],
  },
  {
    ...EDITORIAL,
    slug: "extended_quickdraw_mag",
    name: "Extended Quickdraw Mag",
    slot: "magazine",
    compatibleClasses: ["ar", "smg", "dmr", "sr", "pistol"],
    description: "Capacity and reload speed in one slot — the endgame magazine.",
    effects: [
      { key: "magazine_capacity", direction: "improves", magnitude: "major", note: null },
      { key: "reload_speed", direction: "improves", magnitude: "moderate", note: null },
    ],
  },
  {
    ...EDITORIAL,
    slug: "tactical_stock",
    name: "Tactical Stock",
    slot: "stock",
    compatibleClasses: ["ar", "smg"],
    description: "Recoil and sway stabilizer for M416, Vector, and friends.",
    effects: [
      { key: "vertical_recoil", direction: "improves", magnitude: "minor", note: null },
      { key: "weapon_sway", direction: "improves", magnitude: "moderate", note: null },
    ],
  },
  {
    ...EDITORIAL,
    slug: "cheek_pad",
    name: "Cheek Pad",
    slot: "stock",
    compatibleClasses: ["dmr", "sr"],
    description: "Reduces sway and recoil recovery time on precision rifles.",
    effects: [
      { key: "weapon_sway", direction: "improves", magnitude: "moderate", note: null },
      { key: "recoil_recovery", direction: "improves", magnitude: "minor", note: null },
    ],
  },
];
