import { z } from "zod";

export const settingExplainerSchema = z.object({
  slug: z.string().regex(/^[a-z0-9_]{2,60}$/),
  name: z.string().min(2),
  category: z.enum([
    "aiming",
    "controls",
    "gyroscope",
    "graphics",
    "audio",
    "gameplay",
    "accessibility",
  ]),
  whatItDoes: z.string().min(10),
  whatItDoesNot: z.string().nullable(),
  advantages: z.string().nullable(),
  disadvantages: z.string().nullable(),
  beginnerRec: z.string().nullable(),
  competitiveRec: z.string().nullable(),
  modeNotes: z.string().nullable(),
  deviceImpact: z.string().nullable(),
  retestAfterUpdate: z.boolean(),
});
export type SettingExplainer = z.infer<typeof settingExplainerSchema>;

/**
 * Settings library (spec §5.6): ≥30 explainers. Editorial content, stored
 * unverified; no setting is ever promised to produce an outcome.
 */
export const SETTING_EXPLAINERS: SettingExplainer[] = [
  {
    slug: "aim_assist",
    name: "Aim assist",
    category: "aiming",
    whatItDoes: "Applies slight magnetism toward targets while ADS firing, smoothing small tracking errors.",
    whatItDoesNot: "It does not control recoil, flick for you, or work in Ultimate Royale where it is disabled.",
    advantages: "More forgiving tracking, especially on smaller screens and lower touch precision.",
    disadvantages: "Can drag your aim between multiple targets and hides tracking weaknesses you'll need in UR.",
    beginnerRec: "On, until your manual tracking is consistent.",
    competitiveRec: "Train with it off if you play Ultimate Royale or tournament rules; use the A/B lab rather than guessing.",
    modeNotes: "Disabled by rule in Ultimate Royale (unverified for the current season until officially confirmed).",
    deviceImpact: null,
    retestAfterUpdate: true,
  },
  {
    slug: "gyroscope",
    name: "Gyroscope",
    category: "gyroscope",
    whatItDoes: "Moves your camera with physical device rotation, adding a second precise input channel.",
    whatItDoesNot: "It does not remove recoil — it gives you another way to counteract it manually.",
    advantages: "Fine recoil control and micro-tracking without thumb travel.",
    disadvantages: "Weeks of retraining, posture sensitivity, and drift on some devices.",
    beginnerRec: "Off or scope-on while learning fundamentals.",
    competitiveRec: "Scope-on or always-on is common at high ranks, but only with deliberate practice.",
    modeNotes: null,
    deviceImpact: "Gyro sensor quality varies by device; run the drift check in calibration.",
    retestAfterUpdate: true,
  },
  {
    slug: "ads_gyroscope",
    name: "ADS gyroscope",
    category: "gyroscope",
    whatItDoes: "Separate gyro sensitivity applied only while aiming down sights.",
    whatItDoesNot: null,
    advantages: "Lets you keep hip-fire gyro calm while using strong gyro control in scopes.",
    disadvantages: "One more layer to calibrate per scope.",
    beginnerRec: "Leave matched to gyro defaults until comfortable.",
    competitiveRec: "Calibrate per scope with the spray tests — one variable at a time.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: true,
  },
  {
    slug: "camera_sensitivity",
    name: "Camera sensitivity",
    category: "aiming",
    whatItDoes: "Controls how fast the camera turns from swipes when not aiming down sights.",
    whatItDoesNot: "It does not affect ADS aim — that's ADS sensitivity.",
    advantages: "Higher values turn faster for checking flanks; lower values steady your general view.",
    disadvantages: "Too high causes overshooting on turns; too low loses fights to flanks.",
    beginnerRec: "Start near defaults; use the 90°/180° turn tests to tune.",
    competitiveRec: "Tune to consistently land 90° and 180° turns — speed you can't stop isn't speed.",
    modeNotes: null,
    deviceImpact: "Screen size changes effective swipe distance; recalibrate after device changes.",
    retestAfterUpdate: false,
  },
  {
    slug: "ads_sensitivity",
    name: "ADS sensitivity",
    category: "aiming",
    whatItDoes: "Per-scope aim speed while firing down sights — the core spray-control setting.",
    whatItDoesNot: "It does not change recoil magnitude, only how your corrections translate.",
    advantages: "Per-scope tuning lets your 3× spray and 8× micro-adjustments both feel right.",
    disadvantages: "Copying someone else's values ignores your device, grip, and FPS.",
    beginnerRec: "Calibrate red dot and 3× first; they cover most fights.",
    competitiveRec: "Full per-scope calibration, retested after relevant balance patches.",
    modeNotes: null,
    deviceImpact: "Touch sampling and FPS change how corrections register.",
    retestAfterUpdate: true,
  },
  {
    slug: "free_look_sensitivity",
    name: "Free look sensitivity",
    category: "aiming",
    whatItDoes: "Speed of the eye-button camera that looks around without turning your character.",
    whatItDoesNot: null,
    advantages: "Fast awareness while running straight lines or gliding.",
    disadvantages: "Very high values disorient more than they inform.",
    beginnerRec: "Defaults are fine.",
    competitiveRec: "High enough to check a full circle in one swipe.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "camera_rotation_ads",
    name: "Camera rotation while ADS",
    category: "aiming",
    whatItDoes: "Allows turning the camera while holding ADS on bolt-actions and specific interactions.",
    whatItDoesNot: null,
    advantages: "Keeps awareness during slow scoping.",
    disadvantages: "Occasional accidental camera movement during precise shots.",
    beginnerRec: "On.",
    competitiveRec: "On.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "peek_and_fire",
    name: "Peek & fire",
    category: "controls",
    whatItDoes: "Adds lean buttons so you can expose only part of your body while shooting.",
    whatItDoesNot: "It does not make you harder to hit while fully exposed — positioning still decides that.",
    advantages: "Smaller target profile in ranged fights and on ridgelines.",
    disadvantages: "Two more buttons competing for screen space and fingers.",
    beginnerRec: "Off until your base layout is comfortable.",
    competitiveRec: "On — ridge fights and window duels demand it.",
    modeNotes: "Essential in Ultimate Royale's slower, cover-based fights.",
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "peek_open_scope",
    name: "Peek & open scope",
    category: "controls",
    whatItDoes: "Automatically ADS when you press a lean button.",
    whatItDoesNot: null,
    advantages: "One input instead of two for the most common peek action.",
    disadvantages: "Forces ADS when you only wanted to look.",
    beginnerRec: "Try both; keep what confuses you less.",
    competitiveRec: "Player preference — consistency matters more than the choice.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "lean_mode",
    name: "Lean mode (tap vs hold)",
    category: "controls",
    whatItDoes: "Whether lean buttons toggle or require holding.",
    whatItDoesNot: null,
    advantages: "Hold gives finer control; tap frees a finger during long peeks.",
    disadvantages: "Toggle can leave you leaning when you meant to reset.",
    beginnerRec: "Tap (toggle).",
    competitiveRec: "Hold, if your grip has a spare finger.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "scope_mode",
    name: "Scope mode (tap vs hold)",
    category: "controls",
    whatItDoes: "Whether ADS toggles on tap or lasts only while held.",
    whatItDoesNot: null,
    advantages: "Hold naturally quick-scopes; tap suits long tracking sprays.",
    disadvantages: "Hold occupies a finger through every fight.",
    beginnerRec: "Tap.",
    competitiveRec: "Many close-range specialists use hold for shotguns/SMGs — test in Arena.",
    modeNotes: "Arena's constant close fights are the best testbed.",
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "quick_scope_switch",
    name: "Quick scope switch",
    category: "controls",
    whatItDoes: "Adds a button to swap between two scope magnifications on the fly.",
    whatItDoesNot: null,
    advantages: "6× zoomed to 3× spraying without opening the backpack.",
    disadvantages: "Another button to place; rarely used by beginners.",
    beginnerRec: "Off.",
    competitiveRec: "On for DMR/6× users.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "bolt_action_fire_mode",
    name: "Bolt-action firing mode",
    category: "controls",
    whatItDoes: "Choose whether bolt-action rifles fire on release or on tap while scoped.",
    whatItDoesNot: null,
    advantages: "Release-to-fire enables drag-shot timing.",
    disadvantages: "Release mode causes accidental shots while adjusting.",
    beginnerRec: "Tap to fire.",
    competitiveRec: "Test release mode only if you snipe a lot.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "shotgun_fire_mode",
    name: "Shotgun firing mode",
    category: "controls",
    whatItDoes: "Configures tap vs release firing for shotguns.",
    whatItDoesNot: null,
    advantages: "Matches shotgun timing to your jiggle rhythm.",
    disadvantages: null,
    beginnerRec: "Default.",
    competitiveRec: "Preference; consistency wins.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "left_side_fire_button",
    name: "Left-side fire button",
    category: "controls",
    whatItDoes: "Adds a mirrored fire button on the left so you can shoot while steering.",
    whatItDoesNot: null,
    advantages: "Two-finger players can fire without abandoning movement.",
    disadvantages: "Accidental shots reveal your position.",
    beginnerRec: "On for two-finger layouts.",
    competitiveRec: "Usually off with 4+ fingers — the index finger handles fire.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "fixed_joystick",
    name: "Fixed vs floating joystick",
    category: "controls",
    whatItDoes: "Whether the movement stick stays anchored or appears where your thumb lands.",
    whatItDoesNot: null,
    advantages: "Fixed builds muscle memory; floating forgives sloppy thumb placement.",
    disadvantages: "Fixed punishes off-center presses; floating drifts your anchor mid-fight.",
    beginnerRec: "Floating.",
    competitiveRec: "Split preference among top players — commit to one.",
    modeNotes: null,
    deviceImpact: "Larger screens favor fixed placement.",
    retestAfterUpdate: false,
  },
  {
    slug: "joystick_size",
    name: "Joystick size",
    category: "controls",
    whatItDoes: "Scales the movement stick's touch area.",
    whatItDoesNot: null,
    advantages: "Bigger sticks are harder to slip off during jiggles.",
    disadvantages: "Oversized sticks crowd nearby buttons.",
    beginnerRec: "Slightly larger than default.",
    competitiveRec: "As large as your layout allows without collisions.",
    modeNotes: null,
    deviceImpact: "Tablets can afford much larger sticks.",
    retestAfterUpdate: false,
  },
  {
    slug: "sprint_activation",
    name: "Sprint activation",
    category: "controls",
    whatItDoes: "Configures how sprint engages from the joystick (push distance / auto-sprint zone).",
    whatItDoesNot: null,
    advantages: "Reliable sprint without over-pushing your thumb.",
    disadvantages: "Aggressive auto-sprint can trigger during careful strafes.",
    beginnerRec: "Default.",
    competitiveRec: "Tune so jiggle strafes never accidentally sprint.",
    modeNotes: "Critical in Arena where strafing accuracy decides fights.",
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "healing_prompt",
    name: "Smart healing prompt",
    category: "gameplay",
    whatItDoes: "Suggests a context-appropriate healing item on one button.",
    whatItDoesNot: "It does not always pick what a human would — check before long heals.",
    advantages: "Faster heals under pressure.",
    disadvantages: "Occasionally wastes a big heal where a bandage sufficed.",
    beginnerRec: "On.",
    competitiveRec: "On, but learn manual overrides for endgame item discipline.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "auto_open_doors",
    name: "Auto-open doors",
    category: "gameplay",
    whatItDoes: "Opens doors automatically when you run into them.",
    whatItDoesNot: null,
    advantages: "Smoother pushes without a button press.",
    disadvantages: "Announces entries you wanted silent and opens doors mid-jiggle.",
    beginnerRec: "On.",
    competitiveRec: "Off — door control is information control.",
    modeNotes: "Ultimate Royale players usually disable it.",
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "auto_pickup",
    name: "Auto-pickup",
    category: "gameplay",
    whatItDoes: "Collects configured loot automatically as you walk over it.",
    whatItDoesNot: "It does not manage your backpack mid-fight — tune the pickup list.",
    advantages: "Dramatically faster early loot phase.",
    disadvantages: "Can swap attachments or fill your bag with unwanted ammo at the worst time.",
    beginnerRec: "On with defaults.",
    competitiveRec: "On with a curated list; disable attachment auto-swap.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: true,
  },
  {
    slug: "throwables_quick_wheel",
    name: "Throwables quick wheel",
    category: "controls",
    whatItDoes: "Hold the grenade button to pick a specific throwable from a radial menu.",
    whatItDoesNot: null,
    advantages: "Smoke → frag → stun sequencing without the backpack.",
    disadvantages: "Wheel time is exposure time.",
    beginnerRec: "On.",
    competitiveRec: "On — utility sequencing is a core endgame skill.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "throwable_trajectory",
    name: "Throwable trajectory display",
    category: "gameplay",
    whatItDoes: "Shows the arc your grenade will follow before release.",
    whatItDoesNot: "It does not time your cook — that's on you.",
    advantages: "Reliable bank throws and window lobs.",
    disadvantages: "Slight visual clutter.",
    beginnerRec: "On.",
    competitiveRec: "On.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "canted_sight_behavior",
    name: "Canted sight behavior",
    category: "controls",
    whatItDoes: "Configures how you switch between primary scope and canted sight.",
    whatItDoesNot: null,
    advantages: "Instant 1× answer on a 6× DMR.",
    disadvantages: "One more state to track mid-fight.",
    beginnerRec: "Ignore canted sights at first.",
    competitiveRec: "Practice the swap until it's reflex for DMR builds.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "fpp_swap",
    name: "FPP swap button",
    category: "controls",
    whatItDoes: "Adds a button to switch between TPP and FPP cameras mid-match where allowed.",
    whatItDoesNot: null,
    advantages: "FPP removes third-person peeking advantage checks in buildings.",
    disadvantages: "Extra button; disorienting if rarely used.",
    beginnerRec: "Off.",
    competitiveRec: "Preference; some anchors use FPP indoors.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "tpp_camera_view",
    name: "TPP camera field of view",
    category: "graphics",
    whatItDoes: "Widens or narrows the third-person camera's field of view.",
    whatItDoesNot: "It does not change ADS zoom levels.",
    advantages: "Wider view shows more flanks.",
    disadvantages: "Targets appear smaller at range; some devices lose FPS.",
    beginnerRec: "Default.",
    competitiveRec: "Wider if your device holds frame rate.",
    modeNotes: null,
    deviceImpact: "FOV increases GPU load.",
    retestAfterUpdate: false,
  },
  {
    slug: "hit_marker",
    name: "Hit markers & damage feedback",
    category: "gameplay",
    whatItDoes: "Visual confirmation when your shots connect.",
    whatItDoesNot: "It does not show exact damage in most modes.",
    advantages: "Confirms sprays at range and through smoke edges.",
    disadvantages: "Minimal.",
    beginnerRec: "On.",
    competitiveRec: "On.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "sound_quality",
    name: "Sound quality",
    category: "audio",
    whatItDoes: "Selects the audio processing tier for footsteps, gunshots, and vehicles.",
    whatItDoesNot: "It cannot overcome bad earbuds — hardware matters more.",
    advantages: "Higher tiers separate footstep layers more cleanly.",
    disadvantages: "Slight battery/CPU cost.",
    beginnerRec: "High, with any stereo earphones.",
    competitiveRec: "Highest your device sustains without thermal throttling.",
    modeNotes: null,
    deviceImpact: "Thermal throttling can cost more than the audio tier gains.",
    retestAfterUpdate: false,
  },
  {
    slug: "graphics_quality",
    name: "Graphics quality",
    category: "graphics",
    whatItDoes: "Overall render quality preset.",
    whatItDoesNot: "Higher quality does not improve visibility as much as stable FPS does.",
    advantages: "Prettier matches on capable devices.",
    disadvantages: "Blocks higher frame-rate tiers on many devices.",
    beginnerRec: "Smooth preset.",
    competitiveRec: "Smooth — always trade quality for frame rate.",
    modeNotes: null,
    deviceImpact: "The main lever for unlocking your device's top FPS tier.",
    retestAfterUpdate: true,
  },
  {
    slug: "frame_rate",
    name: "Frame rate",
    category: "graphics",
    whatItDoes: "Caps the game's target FPS from the tiers your device supports.",
    whatItDoesNot: "A higher cap doesn't help if your device can't hold it steadily.",
    advantages: "Higher stable FPS improves tracking feel and input response.",
    disadvantages: "Battery drain and heat; unstable high FPS is worse than stable lower FPS.",
    beginnerRec: "Highest tier your device holds without stutter.",
    competitiveRec: "Same — stability first; sensitivity must be recalibrated after FPS changes.",
    modeNotes: null,
    deviceImpact: "Supported tiers vary by device and version — verify per device.",
    retestAfterUpdate: true,
  },
  {
    slug: "anti_aliasing",
    name: "Anti-aliasing",
    category: "graphics",
    whatItDoes: "Smooths jagged edges on distant geometry.",
    whatItDoesNot: null,
    advantages: "Cleaner long-range silhouettes.",
    disadvantages: "Meaningful FPS cost on mid-range devices.",
    beginnerRec: "Off if FPS matters.",
    competitiveRec: "Off unless your device has headroom.",
    modeNotes: null,
    deviceImpact: "One of the cheapest wins for regaining frame rate.",
    retestAfterUpdate: false,
  },
  {
    slug: "brightness",
    name: "Brightness",
    category: "graphics",
    whatItDoes: "In-game brightness curve on top of your device's screen brightness.",
    whatItDoesNot: null,
    advantages: "Lifting shadows reveals players in dark interiors.",
    disadvantages: "Washed-out contrast at extremes.",
    beginnerRec: "Slightly above default.",
    competitiveRec: "Tuned per map — brighter for Vikendi interiors, default for Miramar.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "colorblind_modes",
    name: "Colorblind modes",
    category: "accessibility",
    whatItDoes: "Remaps key colors (blood, zone, markers) for common color-vision differences.",
    whatItDoesNot: null,
    advantages: "Critical information stops relying on colors you can't separate.",
    disadvantages: "None.",
    beginnerRec: "Use the mode matching your vision.",
    competitiveRec: "Some non-colorblind players prefer certain modes for zone clarity — legitimate to test.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "death_replay",
    name: "Death replay",
    category: "gameplay",
    whatItDoes: "Records a short replay showing how you were knocked or killed.",
    whatItDoesNot: "It is not a cheat detector — network views differ from the killer's screen.",
    advantages: "The single best free coaching tool: see your exposure mistakes.",
    disadvantages: "Small storage/processing cost.",
    beginnerRec: "On — watch every death.",
    competitiveRec: "On — review deaths for positioning patterns, not just aim.",
    modeNotes: null,
    deviceImpact: null,
    retestAfterUpdate: false,
  },
  {
    slug: "haptic_feedback",
    name: "Haptic feedback",
    category: "controls",
    whatItDoes: "Vibrates on hits, kills, and interactions.",
    whatItDoesNot: null,
    advantages: "Physical confirmation without watching the HUD.",
    disadvantages: "Vibration can blur gyro aim on some devices.",
    beginnerRec: "Preference.",
    competitiveRec: "Gyro players usually disable it.",
    modeNotes: null,
    deviceImpact: "Interferes with gyroscope stability on lighter phones.",
    retestAfterUpdate: false,
  },
];
