import type { SourceRecord } from "../schemas";

/** Research sources captured in DATA_VERIFICATION.md (2026-07-21 pass). */
export const SOURCES: SourceRecord[] = [
  {
    key: "vpesports-45",
    name: "vpesports — PUBG Mobile 4.5 patch schedule",
    url: "https://vpesports.com/games/pubg/pubg-mobile-summer-2026",
    sourceType: "news",
    publishedOn: null,
    retrievedOn: "2026-07-21",
    reliability: "medium",
    notes: "Secondary source; corroborates 4.5 launch and window.",
  },
  {
    key: "sportsdunia-45",
    name: "SportsDunia — PUBG Mobile 4.5 update release",
    url: "https://www.sportsdunia.com/gaming/pubg-mobile-4-5-update-to-go-live",
    sourceType: "news",
    publishedOn: null,
    retrievedOn: "2026-07-21",
    reliability: "medium",
    notes: null,
  },
  {
    key: "enjoygm-45",
    name: "EnjoyGM — PUBG Mobile 4.5 update walkthrough",
    url: "https://www.enjoygm.com/blog/pubg-mobile/pubg-mobile-4-5-update",
    sourceType: "news",
    publishedOn: null,
    retrievedOn: "2026-07-21",
    reliability: "low",
    notes: null,
  },
  {
    key: "topuplive-s31",
    name: "TopupLive — PUBG Mobile Season 31 update",
    url: "https://www.topuplive.com/news/pubg-mobile-season-31-update.html",
    sourceType: "news",
    publishedOn: null,
    retrievedOn: "2026-07-21",
    reliability: "medium",
    notes: "S31 Classic dates and Ultimate Royale start date.",
  },
  {
    key: "sportsdunia-balance",
    name: "SportsDunia — PUBG Mobile 4.4/4.5 weapon balance changes",
    url: "https://www.sportsdunia.com/gaming/pubg-mobile-4-4-beta-weapon-balance-changes",
    sourceType: "news",
    publishedOn: null,
    retrievedOn: "2026-07-21",
    reliability: "low",
    notes: "Beta-notes coverage of ACE32 and SMG changes; magnitudes unknown.",
  },
  {
    key: "gamingonphone-ur",
    name: "GamingOnPhone — Ultimate Royale mode rules",
    url: "https://gamingonphone.com/news/pubg-mobile-ultimate-royale-mode/",
    sourceType: "news",
    publishedOn: null,
    retrievedOn: "2026-07-21",
    reliability: "medium",
    notes: "Aim assist disabled, no shop/flare, Crown-tier entry, esports zones.",
  },
  {
    key: "gamespress-45",
    name: "GamesPress — official 4.5 press release (Naruto collaboration)",
    url: "https://www.gamespress.com/PUBG-MOBILES-VERSION-45-UPDATE-INTRODUCES-ONE-OF-ITS-BIGGEST-EVER-COLL",
    sourceType: "press",
    publishedOn: null,
    retrievedOn: "2026-07-21",
    reliability: "medium",
    notes: "Official PR distribution channel; strongest source captured this pass.",
  },
];
