import { z } from "zod";

/**
 * Training academy content (spec §5.10). Drills are editorial designs with
 * self-measurable pass criteria — stored unverified, never promising outcomes.
 * WoW directory entries ship WITHOUT map codes: codes are real-world facts and
 * are never invented (rows carry status 'unverified' until an editor verifies).
 */

export const skillSchema = z.object({
  slug: z.string().regex(/^[a-z0-9_]{2,50}$/),
  name: z.string().min(2),
  category: z.string().regex(/^[a-z0-9_]{2,40}$/),
  description: z.string().min(10),
  sortOrder: z.number().int(),
});
export type SkillRecord = z.infer<typeof skillSchema>;

export const drillSchema = z.object({
  slug: z.string().regex(/^[a-z0-9_]{2,60}$/),
  name: z.string().min(3),
  skillSlug: z.string(),
  objective: z.string().min(10),
  difficulty: z.enum(["beginner", "intermediate", "advanced"]),
  prerequisites: z.string().nullable(),
  requiredMode: z.string().nullable(),
  weaponNote: z.string().nullable(),
  scopeNote: z.string().nullable(),
  distanceNote: z.string().nullable(),
  stanceNote: z.string().nullable(),
  durationMinutes: z.number().int().min(1).max(60),
  repetitions: z.string().nullable(),
  passingScore: z.string().min(5),
  advancedScore: z.string().nullable(),
  commonMistakes: z.string().nullable(),
  coachingCues: z.string().nullable(),
  progressionSlug: z.string().nullable(),
  applicableModes: z.array(z.string()),
  aimAssistVariant: z.enum(["on", "off", "both"]).nullable(),
});
export type DrillRecord = z.infer<typeof drillSchema>;

export const planSchema = z.object({
  slug: z.string().regex(/^[a-z0-9_]{2,60}$/),
  name: z.string().min(3),
  description: z.string().min(10),
  minutes: z.union([
    z.literal(5), z.literal(10), z.literal(15), z.literal(30), z.literal(45), z.literal(60),
  ]),
  focusCategories: z.array(z.string()),
  aimAssistFocus: z.enum(["on", "off", "mixed"]).nullable(),
  items: z
    .array(z.object({ drillSlug: z.string(), minutes: z.number().int().min(1).max(60), note: z.string().nullable() }))
    .min(1),
});
export type PlanRecord = z.infer<typeof planSchema>;

export const wowMapSchema = z.object({
  slug: z.string().regex(/^[a-z0-9_-]{2,60}$/),
  name: z.string().min(3),
  creatorLabel: z.string().nullable(),
  /** ALWAYS null in seeds — real codes enter via editorial verification only. */
  mapCode: z.null(),
  category: z.string(),
  playerCount: z.string().nullable(),
  rules: z.string().nullable(),
});
export type WowMapRecord = z.infer<typeof wowMapSchema>;

export const SKILLS: SkillRecord[] = [
  { slug: "crosshair_placement", name: "Crosshair placement", category: "aim", description: "Keeping the crosshair at head height where enemies will appear.", sortOrder: 10 },
  { slug: "tracking", name: "Tracking", category: "aim", description: "Holding the crosshair on a moving target.", sortOrder: 20 },
  { slug: "flicking", name: "Flicking", category: "aim", description: "Fast precise snaps to a new target.", sortOrder: 30 },
  { slug: "target_switching", name: "Target switching", category: "aim", description: "Committing kills across multiple targets without over-swinging.", sortOrder: 40 },
  { slug: "recoil_short", name: "Short-burst recoil", category: "recoil", description: "Controlling the first 10 bullets where fights are decided.", sortOrder: 10 },
  { slug: "recoil_spray", name: "Full-magazine sprays", category: "recoil", description: "Keeping long sprays on target across scopes and stances.", sortOrder: 20 },
  { slug: "jiggle_movement", name: "Jiggle movement", category: "close_range", description: "Strafing patterns that break enemy tracking up close.", sortOrder: 10 },
  { slug: "entry_mechanics", name: "Entry mechanics", category: "close_range", description: "Room entries, pre-fire angles, and crouch/jump timing.", sortOrder: 20 },
  { slug: "hip_fire", name: "Hip fire", category: "close_range", description: "No-ADS accuracy inside 10 meters.", sortOrder: 30 },
  { slug: "burst_control", name: "Burst control", category: "mid_range", description: "Grouped 3–5 round bursts at mid range.", sortOrder: 10 },
  { slug: "spray_transfer", name: "Spray transfers", category: "mid_range", description: "Moving a controlled spray between targets.", sortOrder: 20 },
  { slug: "peek_discipline", name: "Peek discipline", category: "mid_range", description: "Short exposure windows and re-peek variation.", sortOrder: 30 },
  { slug: "dmr_cadence", name: "DMR cadence", category: "long_range", description: "Sustainable accurate fire rate with marksman rifles.", sortOrder: 10 },
  { slug: "sniper_precision", name: "Sniper precision", category: "long_range", description: "Bolt-action micro-adjustments, drop, and lead.", sortOrder: 20 },
  { slug: "joystick_control", name: "Joystick control", category: "movement", description: "Clean strafes, sprint management, and camera separation.", sortOrder: 10 },
  { slug: "cover_movement", name: "Cover movement", category: "movement", description: "Cover-to-cover routes that minimize exposure.", sortOrder: 20 },
  { slug: "footstep_reading", name: "Footstep reading", category: "audio", description: "Direction, floor, and distance from sound alone.", sortOrder: 10 },
  { slug: "utility_throws", name: "Utility throws", category: "throwables", description: "Frag timing, cooking, banks, and smoke placement.", sortOrder: 10 },
  { slug: "rotation_planning", name: "Rotation planning", category: "br_intelligence", description: "When and how to move between zones and compounds.", sortOrder: 10 },
  { slug: "trade_discipline", name: "Trade discipline", category: "team_play", description: "Spacing and refrag timing so knocks convert to kills.", sortOrder: 10 },
];

const WOW = "wow";
const ARENA = "arena_casual";
const CASUAL = "classic_casual";

const drill = (d: DrillRecord): DrillRecord => d;

export const DRILLS: DrillRecord[] = [
  // --- Aim: crosshair placement ---
  drill({ slug: "head_height_walls", name: "Head-height wall trace", skillSlug: "crosshair_placement", objective: "Trace head height along walls while moving through a compound.", difficulty: "beginner", prerequisites: null, requiredMode: CASUAL, weaponNote: "Any AR", scopeNote: "Red dot", distanceNote: "Indoors", stanceNote: "Standing", durationMinutes: 5, repetitions: "3 compounds", passingScore: "Crosshair stays within a head of door frames on 8 of 10 entries.", advancedScore: "10 of 10 with no vertical correction on first shot.", commonMistakes: "Drifting to floor level while sprinting.", coachingCues: "Aim where the head will be, not where the door is.", progressionSlug: "prefire_corners", applicableModes: [CASUAL, WOW], aimAssistVariant: null }),
  drill({ slug: "prefire_corners", name: "Pre-fire common angles", skillSlug: "crosshair_placement", objective: "Pre-aim and pre-fire the five most common angles of a compound.", difficulty: "intermediate", prerequisites: "head_height_walls", requiredMode: CASUAL, weaponNote: "Any AR", scopeNote: "Red dot", distanceNote: "5–15m", stanceNote: "Standing", durationMinutes: 6, repetitions: "5 angles × 4 loops", passingScore: "First bullet lands on the head box in 6 of 10 pre-fires.", advancedScore: "8 of 10 while strafing into the angle.", commonMistakes: "Opening fire before the crosshair settles.", coachingCues: "Slice the angle; shoot as the shoulder appears.", progressionSlug: null, applicableModes: [CASUAL, WOW], aimAssistVariant: null }),
  // --- Aim: tracking (incl. the aim-assist A/B pair) ---
  drill({ slug: "strafe_tracking_aa_on", name: "Strafe tracking — aim assist ON", skillSlug: "tracking", objective: "Track a strafing target at 15m for full magazines with aim assist on.", difficulty: "beginner", prerequisites: null, requiredMode: WOW, weaponNote: "UMP45", scopeNote: "Red dot", distanceNote: "15m", stanceNote: "Standing", durationMinutes: 5, repetitions: "5 magazines", passingScore: "60% of shots hit across 5 magazines.", advancedScore: "75% with half the misses in the first 3 bullets only.", commonMistakes: "Letting assist drag you between two targets.", coachingCues: "Move WITH the target, don't chase it.", progressionSlug: "strafe_tracking_aa_off", applicableModes: [WOW, ARENA], aimAssistVariant: "on" }),
  drill({ slug: "strafe_tracking_aa_off", name: "Strafe tracking — aim assist OFF", skillSlug: "tracking", objective: "Repeat the identical tracking drill with aim assist disabled and compare hit rates.", difficulty: "intermediate", prerequisites: "strafe_tracking_aa_on", requiredMode: WOW, weaponNote: "UMP45", scopeNote: "Red dot", distanceNote: "15m", stanceNote: "Standing", durationMinutes: 5, repetitions: "5 magazines", passingScore: "Within 15% of your aim-assist-on hit rate.", advancedScore: "Match your aim-assist-on hit rate.", commonMistakes: "Overcorrecting the moment the target reverses.", coachingCues: "Smooth thumb, small corrections — this is the Ultimate Royale baseline.", progressionSlug: null, applicableModes: [WOW, "ultimate_royale"], aimAssistVariant: "off" }),
  drill({ slug: "vertical_tracking", name: "Vertical tracking on ramps", skillSlug: "tracking", objective: "Hold the crosshair on a target moving up and down ramps and stairs.", difficulty: "intermediate", prerequisites: null, requiredMode: WOW, weaponNote: "M416", scopeNote: "Red dot", distanceNote: "10–20m", stanceNote: "Standing", durationMinutes: 5, repetitions: "4 passes", passingScore: "Stay on the torso for 70% of each pass.", advancedScore: "Stay on the head for 50% of each pass.", commonMistakes: "Forgetting vertical input entirely while strafing.", coachingCues: "Think in arcs, not lines.", progressionSlug: null, applicableModes: [WOW], aimAssistVariant: null }),
  // --- Aim: flicking / switching (incl. A/B pair) ---
  drill({ slug: "two_target_flick", name: "Two-target flick", skillSlug: "flicking", objective: "Alternate single shots between two targets 30° apart.", difficulty: "beginner", prerequisites: null, requiredMode: WOW, weaponNote: "Any DMR", scopeNote: "Red dot", distanceNote: "20m", stanceNote: "Standing", durationMinutes: 4, repetitions: "20 pairs", passingScore: "14 of 20 pairs both hit.", advancedScore: "18 of 20 with under a second per pair.", commonMistakes: "Flicking past and dragging back slowly.", coachingCues: "Flick, stop, confirm, fire.", progressionSlug: "target_switch_aa_off", applicableModes: [WOW], aimAssistVariant: null }),
  drill({ slug: "target_switch_aa_on", name: "Triple switch — aim assist ON", skillSlug: "target_switching", objective: "Clear three targets in a 90° arc, one burst each, aim assist on.", difficulty: "intermediate", prerequisites: null, requiredMode: WOW, weaponNote: "SCAR-L", scopeNote: "Red dot", distanceNote: "12m", stanceNote: "Standing", durationMinutes: 5, repetitions: "10 arcs", passingScore: "All three down within 6 seconds in 6 of 10 arcs.", advancedScore: "Under 4.5 seconds in 6 of 10.", commonMistakes: "Spraying between targets while swinging.", coachingCues: "Release the trigger during every swing.", progressionSlug: "target_switch_aa_off", applicableModes: [WOW, ARENA], aimAssistVariant: "on" }),
  drill({ slug: "target_switch_aa_off", name: "Triple switch — aim assist OFF", skillSlug: "target_switching", objective: "The identical arc with aim assist disabled; log both times in your results.", difficulty: "advanced", prerequisites: "target_switch_aa_on", requiredMode: WOW, weaponNote: "SCAR-L", scopeNote: "Red dot", distanceNote: "12m", stanceNote: "Standing", durationMinutes: 5, repetitions: "10 arcs", passingScore: "Within 1.5s of your aim-assist-on time.", advancedScore: "Match your aim-assist-on time.", commonMistakes: "Swinging past the second target.", coachingCues: "Eyes lead, thumb follows.", progressionSlug: null, applicableModes: [WOW, "ultimate_royale"], aimAssistVariant: "off" }),
  drill({ slug: "reaction_peek", name: "Reaction peek duel", skillSlug: "flicking", objective: "React and fire at a randomly appearing target from behind cover.", difficulty: "intermediate", prerequisites: null, requiredMode: WOW, weaponNote: "AKM", scopeNote: "Red dot", distanceNote: "15m", stanceNote: "Standing", durationMinutes: 5, repetitions: "20 peeks", passingScore: "First hit within 0.8s on 12 of 20 peeks.", advancedScore: "Within 0.6s on 12 of 20.", commonMistakes: "Peeking the same shoulder rhythm every time.", coachingCues: "Vary timing; commit fully when you go.", progressionSlug: null, applicableModes: [WOW], aimAssistVariant: null }),
  // --- Recoil ---
  drill({ slug: "first_ten_reddot", name: "First 10 — red dot", skillSlug: "recoil_short", objective: "Land the first 10 bullets in a head-sized circle at 20m.", difficulty: "beginner", prerequisites: null, requiredMode: WOW, weaponNote: "M416, then your main AR", scopeNote: "Red dot", distanceNote: "20m", stanceNote: "Standing", durationMinutes: 5, repetitions: "10 bursts", passingScore: "7 of 10 bursts fully inside the circle.", advancedScore: "9 of 10, then repeat while crouched.", commonMistakes: "Pulling down before recoil actually starts.", coachingCues: "Match the pull to the kick, don't predict it.", progressionSlug: "first_ten_3x", applicableModes: [WOW], aimAssistVariant: null }),
  drill({ slug: "first_ten_3x", name: "First 10 — 3×", skillSlug: "recoil_short", objective: "The same first-10 discipline through a 3× at 35m.", difficulty: "intermediate", prerequisites: "first_ten_reddot", requiredMode: WOW, weaponNote: "Your main AR", scopeNote: "3×", distanceNote: "35m", stanceNote: "Standing", durationMinutes: 5, repetitions: "10 bursts", passingScore: "6 of 10 bursts inside a torso box.", advancedScore: "8 of 10 inside a head-and-shoulders box.", commonMistakes: "Gripping tighter as magnification grows.", coachingCues: "Same pull, smaller picture.", progressionSlug: "full_mag_3x", applicableModes: [WOW], aimAssistVariant: null }),
  drill({ slug: "full_mag_reddot", name: "Full magazine — red dot", skillSlug: "recoil_spray", objective: "Keep an entire magazine on a torso target at 20m.", difficulty: "beginner", prerequisites: "first_ten_reddot", requiredMode: WOW, weaponNote: "M416", scopeNote: "Red dot", distanceNote: "20m", stanceNote: "Standing", durationMinutes: 5, repetitions: "6 magazines", passingScore: "70% of each magazine on the torso.", advancedScore: "85% with bullets 20+ still grouped.", commonMistakes: "Giving up on the last third of the spray.", coachingCues: "The end of the mag is where sprays are won.", progressionSlug: "full_mag_3x", applicableModes: [WOW], aimAssistVariant: null }),
  drill({ slug: "full_mag_3x", name: "Full magazine — 3×", skillSlug: "recoil_spray", objective: "Full-mag control through a 3× at 35m, tracking horizontal drift.", difficulty: "advanced", prerequisites: "full_mag_reddot", requiredMode: WOW, weaponNote: "Your main AR", scopeNote: "3×", distanceNote: "35m", stanceNote: "Standing, then crouched", durationMinutes: 6, repetitions: "6 magazines", passingScore: "60% on torso; note WHERE the spray escapes (left/right/late).", advancedScore: "75% with symmetrical horizontal spread.", commonMistakes: "Blaming sensitivity for what is a grip problem.", coachingCues: "If spread is one-sided, your thumb anchor is tilted.", progressionSlug: null, applicableModes: [WOW], aimAssistVariant: null }),
  drill({ slug: "crouch_spray_transition", name: "Stand-to-crouch spray", skillSlug: "recoil_spray", objective: "Crouch mid-magazine without losing the target.", difficulty: "intermediate", prerequisites: "full_mag_reddot", requiredMode: WOW, weaponNote: "Beryl M762 for punishment", scopeNote: "Red dot", distanceNote: "20m", stanceNote: "Stand → crouch at bullet ~12", durationMinutes: 5, repetitions: "8 magazines", passingScore: "No more than 3 lost bullets during the transition.", advancedScore: "Zero lost bullets on 6 of 8.", commonMistakes: "Crouching and pausing the pull simultaneously.", coachingCues: "The crouch cancels recoil for one beat — keep pulling anyway.", progressionSlug: null, applicableModes: [WOW], aimAssistVariant: null }),
  drill({ slug: "moving_spray", name: "Strafing spray", skillSlug: "recoil_spray", objective: "Spray accurately while jiggle-strafing at close range.", difficulty: "advanced", prerequisites: "crouch_spray_transition", requiredMode: WOW, weaponNote: "Vector or UMP45", scopeNote: "Red dot", distanceNote: "10m", stanceNote: "Strafing", durationMinutes: 5, repetitions: "8 magazines", passingScore: "65% hits while never standing still.", advancedScore: "80% while switching strafe direction twice per mag.", commonMistakes: "Stopping to shoot — that's the habit this kills.", coachingCues: "Feet and thumb are independent instruments.", progressionSlug: null, applicableModes: [WOW, ARENA], aimAssistVariant: null }),
  // --- Close range ---
  drill({ slug: "jiggle_basics", name: "Jiggle strafe basics", skillSlug: "jiggle_movement", objective: "Learn A-D jiggle rhythm that desyncs enemy tracking.", difficulty: "beginner", prerequisites: null, requiredMode: ARENA, weaponNote: "Any SMG", scopeNote: "None", distanceNote: "5–10m", stanceNote: "Strafing", durationMinutes: 4, repetitions: "10 fights", passingScore: "Win 4 of 10 close fights you would normally take 50/50.", advancedScore: "Survive first contact in 8 of 10.", commonMistakes: "Even, predictable left-right timing.", coachingCues: "Stutter the rhythm: short-short-long.", progressionSlug: "jiggle_peek_duel", applicableModes: [ARENA, WOW], aimAssistVariant: null }),
  drill({ slug: "jiggle_peek_duel", name: "Jiggle peek duels", skillSlug: "jiggle_movement", objective: "Win repeated duels using edge jiggles to bait shots.", difficulty: "intermediate", prerequisites: "jiggle_basics", requiredMode: ARENA, weaponNote: "AR or SMG", scopeNote: "Red dot", distanceNote: "10–15m", stanceNote: "Cover edge", durationMinutes: 6, repetitions: "10 duels", passingScore: "Bait a miss before committing in 6 of 10 duels.", advancedScore: "8 of 10 with a first-bullet headshot on commit.", commonMistakes: "Full-body peeks on the bait.", coachingCues: "Show a shoulder, never a chest.", progressionSlug: null, applicableModes: [ARENA], aimAssistVariant: null }),
  drill({ slug: "hipfire_circle", name: "Hip-fire circle", skillSlug: "hip_fire", objective: "Circle-strafe a target at 6m landing hip-fire without ADS.", difficulty: "beginner", prerequisites: null, requiredMode: WOW, weaponNote: "UZI", scopeNote: "None", distanceNote: "6m", stanceNote: "Circling", durationMinutes: 4, repetitions: "6 magazines", passingScore: "60% hits over 6 magazines.", advancedScore: "75% while reversing circle direction each mag.", commonMistakes: "Screen-watching the enemy instead of the crosshair.", coachingCues: "Keep the dot pinned; your feet do the aiming.", progressionSlug: null, applicableModes: [WOW, ARENA], aimAssistVariant: null }),
  drill({ slug: "room_entry_pairs", name: "Room entry pairs", skillSlug: "entry_mechanics", objective: "Enter rooms in the two-angle sequence: deep angle first, then near corner.", difficulty: "intermediate", prerequisites: "prefire_corners", requiredMode: CASUAL, weaponNote: "SMG preferred", scopeNote: "Red dot", distanceNote: "Indoors", stanceNote: "Standing", durationMinutes: 6, repetitions: "10 entries", passingScore: "Correct sequence on 8 of 10 entries.", advancedScore: "Add a crouch on the second angle in under 0.5s.", commonMistakes: "Checking the near corner first and dying to the deep angle.", coachingCues: "Deep kills you; near only surprises you.", progressionSlug: null, applicableModes: [CASUAL], aimAssistVariant: null }),
  drill({ slug: "drop_shot_timing", name: "Drop-shot timing", skillSlug: "entry_mechanics", objective: "Prone-drop mid-fight only when cover and range justify it.", difficulty: "advanced", prerequisites: "jiggle_basics", requiredMode: ARENA, weaponNote: "AR", scopeNote: "Red dot", distanceNote: "8–12m", stanceNote: "Stand → prone", durationMinutes: 5, repetitions: "10 fights", passingScore: "Win 5 of 10 fights where you drop; note the 5 where dropping was wrong.", advancedScore: "Call correctly (drop or not) in 8 of 10 before engaging.", commonMistakes: "Dropping in the open where prone means dead.", coachingCues: "Drop-shot is a corner tool, not a reflex.", progressionSlug: null, applicableModes: [ARENA], aimAssistVariant: null }),
  // --- Mid range ---
  drill({ slug: "burst_grouping", name: "Burst grouping ladder", skillSlug: "burst_control", objective: "4-round bursts at 50m, walking hits up from torso to head.", difficulty: "beginner", prerequisites: "first_ten_reddot", requiredMode: WOW, weaponNote: "M416 or SCAR-L", scopeNote: "2×", distanceNote: "50m", stanceNote: "Crouched", durationMinutes: 5, repetitions: "12 bursts", passingScore: "8 of 12 bursts with 3+ hits.", advancedScore: "First bullet on head level in 8 of 12.", commonMistakes: "Bursting faster than the reset.", coachingCues: "Let the gun settle; cadence beats speed.", progressionSlug: "spray_transfer_pairs", applicableModes: [WOW], aimAssistVariant: null }),
  drill({ slug: "spray_transfer_pairs", name: "Spray transfer pairs", skillSlug: "spray_transfer", objective: "Down two targets 10° apart with one continuous magazine.", difficulty: "advanced", prerequisites: "full_mag_3x", requiredMode: WOW, weaponNote: "Your main AR", scopeNote: "3×", distanceNote: "30m", stanceNote: "Crouched", durationMinutes: 6, repetitions: "8 magazines", passingScore: "Both targets down in 6 of 8 magazines.", advancedScore: "Transfer without any recovery pause in 6 of 8.", commonMistakes: "Lifting the pull during the transfer swing.", coachingCues: "The transfer is sideways, the pull never stops.", progressionSlug: null, applicableModes: [WOW], aimAssistVariant: null }),
  drill({ slug: "peek_timer", name: "Three-second peek budget", skillSlug: "peek_discipline", objective: "Take mid-range fights with a hard 3-second exposure budget.", difficulty: "intermediate", prerequisites: null, requiredMode: CASUAL, weaponNote: "Any AR + 3×", scopeNote: "3×", distanceNote: "50–150m", stanceNote: "Cover", durationMinutes: 8, repetitions: "10 engagements", passingScore: "Break contact within budget in 8 of 10 engagements.", advancedScore: "Land damage in 6 of 10 while never exceeding budget.", commonMistakes: "Re-peeking the same head position.", coachingCues: "One angle, one look; move a body-width between peeks.", progressionSlug: null, applicableModes: [CASUAL, "classic_ranked"], aimAssistVariant: null }),
  // --- Long range ---
  drill({ slug: "dmr_cadence_100", name: "DMR cadence at 100m", skillSlug: "dmr_cadence", objective: "Find your fastest cadence that keeps 8 of 10 shots on a torso at 100m.", difficulty: "intermediate", prerequisites: "burst_grouping", requiredMode: WOW, weaponNote: "Mini14 → SLR", scopeNote: "6× at 3–4 zoom", distanceNote: "100m", stanceNote: "Crouched", durationMinutes: 6, repetitions: "5 strings of 10", passingScore: "8/10 hits at a cadence you can hold for a full string.", advancedScore: "Same accuracy with the SLR.", commonMistakes: "Machine-gunning the trigger and spraying the reset.", coachingCues: "Shoot the settle, not the click.", progressionSlug: null, applicableModes: [WOW], aimAssistVariant: null }),
  drill({ slug: "bolt_micro_adjust", name: "Bolt-action micro-adjust", skillSlug: "sniper_precision", objective: "Move between two head targets 5m apart at 200m and stop precisely.", difficulty: "advanced", prerequisites: null, requiredMode: WOW, weaponNote: "Kar98k or M24", scopeNote: "8×", distanceNote: "200m", stanceNote: "Prone", durationMinutes: 6, repetitions: "20 swaps", passingScore: "Clean stop on the head in 12 of 20 swaps.", advancedScore: "16 of 20 with under 1s per swap.", commonMistakes: "Two corrections per swap instead of one.", coachingCues: "One motion, one stop — retrain until it's singular.", progressionSlug: null, applicableModes: [WOW], aimAssistVariant: null }),
  drill({ slug: "moving_target_lead", name: "Moving target lead", skillSlug: "sniper_precision", objective: "Hit strafing targets at 150m by learning consistent lead.", difficulty: "advanced", prerequisites: "bolt_micro_adjust", requiredMode: WOW, weaponNote: "Kar98k", scopeNote: "8×", distanceNote: "150m", stanceNote: "Crouched", durationMinutes: 6, repetitions: "20 shots", passingScore: "8 of 20 hits on constant-strafe targets.", advancedScore: "12 of 20; log your lead in body-widths for your notes.", commonMistakes: "Tracking through the shot instead of holding the lead point.", coachingCues: "Pick the intercept, hold, fire as they arrive.", progressionSlug: null, applicableModes: [WOW], aimAssistVariant: null }),
  // --- Movement ---
  drill({ slug: "camera_separation", name: "Camera-movement separation", skillSlug: "joystick_control", objective: "Run one direction while sweeping the camera through 360° checks.", difficulty: "beginner", prerequisites: null, requiredMode: CASUAL, weaponNote: null, scopeNote: null, distanceNote: "Open field", stanceNote: "Sprinting", durationMinutes: 4, repetitions: "5 laps", passingScore: "Straight-line path deviates less than 5m during full checks.", advancedScore: "Do it during a zigzag route without rhythm breaks.", commonMistakes: "Slowing down every time the camera moves.", coachingCues: "The left thumb has no idea what the right is doing.", progressionSlug: "cover_route", applicableModes: [CASUAL], aimAssistVariant: null }),
  drill({ slug: "cover_route", name: "Cover-to-cover routes", skillSlug: "cover_movement", objective: "Cross a compound touching only positions with escape cover.", difficulty: "intermediate", prerequisites: "camera_separation", requiredMode: CASUAL, weaponNote: null, scopeNote: null, distanceNote: "Compound scale", stanceNote: "Mixed", durationMinutes: 6, repetitions: "4 crossings", passingScore: "Never more than 3s without reachable cover in 3 of 4 crossings.", advancedScore: "Add a simulated angle-check at every stop.", commonMistakes: "Straight-lining because the compound looks empty.", coachingCues: "Move like someone is always watching the longest sightline.", progressionSlug: null, applicableModes: [CASUAL, "classic_ranked"], aimAssistVariant: null }),
  drill({ slug: "vault_chain", name: "Vault chains", skillSlug: "joystick_control", objective: "Chain vaults over fences and windows without breaking sprint.", difficulty: "beginner", prerequisites: null, requiredMode: CASUAL, weaponNote: null, scopeNote: null, distanceNote: "Compound scale", stanceNote: "Sprinting", durationMinutes: 4, repetitions: "10 chains", passingScore: "8 of 10 chains without a stall.", advancedScore: "Add a 180° check mid-chain.", commonMistakes: "Jumping too early into window frames.", coachingCues: "Vault late, at full speed, dead-center.", progressionSlug: null, applicableModes: [CASUAL], aimAssistVariant: null }),
  // --- Audio ---
  drill({ slug: "blind_direction_calls", name: "Blind direction calls", skillSlug: "footstep_reading", objective: "With eyes off the screen edge, call footstep direction before looking.", difficulty: "beginner", prerequisites: null, requiredMode: CASUAL, weaponNote: null, scopeNote: null, distanceNote: "Hot drop area", stanceNote: "Any", durationMinutes: 8, repetitions: "10 contacts", passingScore: "Correct initial direction on 7 of 10 contacts.", advancedScore: "Correct floor (above/below/same) on 7 of 10 too.", commonMistakes: "Turning before deciding — the turn erases the cue.", coachingCues: "Decide, commit, then turn.", progressionSlug: "distance_bracketing", applicableModes: [CASUAL], aimAssistVariant: null }),
  drill({ slug: "distance_bracketing", name: "Distance bracketing", skillSlug: "footstep_reading", objective: "Bracket footsteps into near/mid/far before visual confirmation.", difficulty: "intermediate", prerequisites: "blind_direction_calls", requiredMode: CASUAL, weaponNote: null, scopeNote: null, distanceNote: "Buildings", stanceNote: "Any", durationMinutes: 8, repetitions: "10 contacts", passingScore: "Correct bracket on 6 of 10.", advancedScore: "8 of 10 including through-floor contacts.", commonMistakes: "Treating loudness alone as distance (occlusion lies).", coachingCues: "Muffled-loud is a floor away; crisp-quiet is far.", progressionSlug: null, applicableModes: [CASUAL], aimAssistVariant: null }),
  // --- Throwables ---
  drill({ slug: "frag_cook_windows", name: "Cooked frags through windows", skillSlug: "utility_throws", objective: "Cook frags to detonate 0.5s after entering a window at 15m.", difficulty: "intermediate", prerequisites: null, requiredMode: WOW, weaponNote: "Frag grenades", scopeNote: null, distanceNote: "15m", stanceNote: "Standing", durationMinutes: 5, repetitions: "10 throws", passingScore: "6 of 10 detonate inside without bounce-back.", advancedScore: "8 of 10 with varied approach angles.", commonMistakes: "Full-arm throws at close windows.", coachingCues: "Cook to 2.5, lob soft, step off the angle.", progressionSlug: "smoke_walls", applicableModes: [WOW, CASUAL], aimAssistVariant: null }),
  drill({ slug: "smoke_walls", name: "Smoke wall placement", skillSlug: "utility_throws", objective: "Build a 3-smoke wall that actually blocks the sightline you intend.", difficulty: "intermediate", prerequisites: null, requiredMode: CASUAL, weaponNote: "Smokes", scopeNote: null, distanceNote: "Open field", stanceNote: "Any", durationMinutes: 6, repetitions: "5 walls", passingScore: "4 of 5 walls fully break the chosen sightline.", advancedScore: "Place while moving, first bounce intentional.", commonMistakes: "Smoking AT the enemy instead of on your own path.", coachingCues: "Smoke covers the runner, not the shooter.", progressionSlug: null, applicableModes: [CASUAL, "classic_ranked"], aimAssistVariant: null }),
  drill({ slug: "bank_throws", name: "Bank throws", skillSlug: "utility_throws", objective: "Bounce frags around corners you cannot see past.", difficulty: "advanced", prerequisites: "frag_cook_windows", requiredMode: WOW, weaponNote: "Frags", scopeNote: null, distanceNote: "Indoors", stanceNote: "Standing", durationMinutes: 5, repetitions: "10 banks", passingScore: "5 of 10 land in the target room.", advancedScore: "7 of 10 cooked to deny the exit.", commonMistakes: "Full-strength banks that skip through the room.", coachingCues: "The wall eats speed — throw one notch harder than feels right.", progressionSlug: null, applicableModes: [WOW], aimAssistVariant: null }),
  // --- BR intelligence ---
  drill({ slug: "rotation_timer", name: "Rotation timing ladder", skillSlug: "rotation_planning", objective: "Leave for zone at the timer mark you planned before looting.", difficulty: "beginner", prerequisites: null, requiredMode: CASUAL, weaponNote: null, scopeNote: null, distanceNote: "Full map", stanceNote: null, durationMinutes: 20, repetitions: "3 matches", passingScore: "Arrive with 30s+ spare in 2 of 3 zones per match.", advancedScore: "Never take zone damage across 3 matches.", commonMistakes: "One more crate syndrome.", coachingCues: "Set the leave time BEFORE you land.", progressionSlug: "edge_rotation", applicableModes: [CASUAL], aimAssistVariant: null }),
  drill({ slug: "edge_rotation", name: "Zone-edge rotations", skillSlug: "rotation_planning", objective: "Rotate along the zone edge clearing one flank by geometry.", difficulty: "intermediate", prerequisites: "rotation_timer", requiredMode: CASUAL, weaponNote: null, scopeNote: null, distanceNote: "Full map", stanceNote: null, durationMinutes: 20, repetitions: "3 matches", passingScore: "Complete 2 of 3 matches never fighting on two fronts.", advancedScore: "Top-10 in all 3 with zero zone damage.", commonMistakes: "Cutting through center to save time.", coachingCues: "The edge is slower and safer — banked time buys fights.", progressionSlug: null, applicableModes: [CASUAL, "classic_ranked"], aimAssistVariant: null }),
  drill({ slug: "loot_speedrun", name: "Two-minute loot standard", skillSlug: "rotation_planning", objective: "Reach AR + scope + 2 heals + vest within 2 minutes of landing.", difficulty: "beginner", prerequisites: null, requiredMode: CASUAL, weaponNote: null, scopeNote: null, distanceNote: "Medium-risk drop", stanceNote: null, durationMinutes: 10, repetitions: "4 drops", passingScore: "Standard met in 3 of 4 drops.", advancedScore: "90 seconds in 3 of 4.", commonMistakes: "Opening every door in a compound you've already outgrown.", coachingCues: "Loot a route, not a building.", progressionSlug: null, applicableModes: [CASUAL], aimAssistVariant: null }),
  // --- Team play ---
  drill({ slug: "trade_spacing", name: "Trade spacing pairs", skillSlug: "trade_discipline", objective: "With a duo partner, hold 10–20m spacing so every knock is traded.", difficulty: "intermediate", prerequisites: null, requiredMode: CASUAL, weaponNote: null, scopeNote: null, distanceNote: "10–20m spacing", stanceNote: null, durationMinutes: 20, repetitions: "3 duo matches", passingScore: "Trade or cover 6 of 8 partner engagements.", advancedScore: "Zero double-knocks from one spray across 3 matches.", commonMistakes: "Stacking through the same door.", coachingCues: "Same fight, different angle — always.", progressionSlug: null, applicableModes: [CASUAL, "classic_ranked"], aimAssistVariant: null }),
  drill({ slug: "focus_fire_calls", name: "Focus-fire calls", skillSlug: "trade_discipline", objective: "Call one target and drop it together before switching.", difficulty: "intermediate", prerequisites: null, requiredMode: CASUAL, weaponNote: null, scopeNote: null, distanceNote: "Squad fights", stanceNote: null, durationMinutes: 20, repetitions: "3 squad matches", passingScore: "First called target drops first in 5 of 8 fights.", advancedScore: "7 of 8 with sub-3s calls.", commonMistakes: "Calling colors nobody bound to compass directions.", coachingCues: "Direction + landmark + target, nothing else.", progressionSlug: null, applicableModes: [CASUAL, "classic_ranked"], aimAssistVariant: null }),
  // --- Extra fundamentals to round the catalog ---
  drill({ slug: "ads_transition_speed", name: "ADS transition reps", skillSlug: "crosshair_placement", objective: "Snap from hip to ADS onto a fixed head target.", difficulty: "beginner", prerequisites: null, requiredMode: WOW, weaponNote: "Your main AR", scopeNote: "Red dot", distanceNote: "15m", stanceNote: "Standing", durationMinutes: 4, repetitions: "20 reps", passingScore: "Sight opens on the head in 12 of 20 reps.", advancedScore: "16 of 20 with a first-shot hit.", commonMistakes: "ADS first, then dragging to the target.", coachingCues: "Place the crosshair before the scope opens.", progressionSlug: null, applicableModes: [WOW], aimAssistVariant: null }),
  drill({ slug: "gyro_stability_hold", name: "Gyro stability hold", skillSlug: "tracking", objective: "Hold a 3× reticle on a 100m target using gyro only for 10 seconds.", difficulty: "intermediate", prerequisites: null, requiredMode: WOW, weaponNote: "Any AR", scopeNote: "3×", distanceNote: "100m", stanceNote: "Standing", durationMinutes: 4, repetitions: "8 holds", passingScore: "6 of 8 holds keep the reticle on the torso throughout.", advancedScore: "On the head for 5 of 8.", commonMistakes: "Death-gripping the phone as the timer runs.", coachingCues: "Loose hands, elbows anchored.", progressionSlug: null, applicableModes: [WOW], aimAssistVariant: null }),
  drill({ slug: "sixty_zoom_spray", name: "6× zoomed-out spray", skillSlug: "recoil_spray", objective: "Use the 6× at 3× zoom for mid-range sprays.", difficulty: "advanced", prerequisites: "full_mag_3x", requiredMode: WOW, weaponNote: "ACE32", scopeNote: "6× at 3", distanceNote: "40m", stanceNote: "Crouched", durationMinutes: 5, repetitions: "6 magazines", passingScore: "55% torso hits per magazine.", advancedScore: "70% and note the ACE32 4.5 recoil feel in results.", commonMistakes: "Leaving the scope at 6× and fighting the sway.", coachingCues: "Zoom down before the fight, not during.", progressionSlug: null, applicableModes: [WOW], aimAssistVariant: null }),
  drill({ slug: "heal_cancel_pressure", name: "Heal-cancel pressure", skillSlug: "entry_mechanics", objective: "Practice canceling heals the instant a push starts.", difficulty: "beginner", prerequisites: null, requiredMode: ARENA, weaponNote: null, scopeNote: null, distanceNote: "Cover", stanceNote: null, durationMinutes: 4, repetitions: "10 reps", passingScore: "Cancel-and-fire within 0.5s in 7 of 10 reps.", advancedScore: "9 of 10 while repositioning.", commonMistakes: "Finishing the bandage out of stubbornness.", coachingCues: "The heal is sunk cost the moment footsteps close.", progressionSlug: null, applicableModes: [ARENA], aimAssistVariant: null }),
  drill({ slug: "vehicle_knock_cadence", name: "Vehicle knock cadence", skillSlug: "dmr_cadence", objective: "Tap moving vehicles at 100–150m with a DMR for consistent chip damage.", difficulty: "intermediate", prerequisites: "dmr_cadence_100", requiredMode: WOW, weaponNote: "SLR", scopeNote: "4×", distanceNote: "100–150m", stanceNote: "Crouched", durationMinutes: 5, repetitions: "5 vehicle passes", passingScore: "6+ hits per pass on 3 of 5 passes.", advancedScore: "10+ hits with early-lead first shots.", commonMistakes: "Tracking the driver instead of leading the hood.", coachingCues: "Shoot where the vehicle will be at bullet arrival.", progressionSlug: null, applicableModes: [WOW], aimAssistVariant: null }),
];

export const TRAINING_PLANS: PlanRecord[] = [
  { slug: "warmup_5", name: "5-minute warmup", description: "The pre-ranked ritual: placement, one spray check.", minutes: 5, focusCategories: ["aim", "recoil"], aimAssistFocus: null, items: [ { drillSlug: "ads_transition_speed", minutes: 2, note: null }, { drillSlug: "first_ten_reddot", minutes: 3, note: null } ] },
  { slug: "aim_10", name: "10-minute aim tune", description: "Placement and tracking basics.", minutes: 10, focusCategories: ["aim"], aimAssistFocus: null, items: [ { drillSlug: "head_height_walls", minutes: 5, note: null }, { drillSlug: "strafe_tracking_aa_on", minutes: 5, note: null } ] },
  { slug: "recoil_15", name: "15-minute recoil block", description: "First-10 discipline into full magazines.", minutes: 15, focusCategories: ["recoil"], aimAssistFocus: null, items: [ { drillSlug: "first_ten_reddot", minutes: 5, note: null }, { drillSlug: "full_mag_reddot", minutes: 5, note: null }, { drillSlug: "crouch_spray_transition", minutes: 5, note: null } ] },
  { slug: "audio_10", name: "10-minute audio reps", description: "Direction and distance from sound.", minutes: 10, focusCategories: ["audio"], aimAssistFocus: null, items: [ { drillSlug: "blind_direction_calls", minutes: 5, note: "Casual match segment" }, { drillSlug: "distance_bracketing", minutes: 5, note: null } ] },
  { slug: "movement_15", name: "15-minute movement flow", description: "Camera separation, vaults, cover routes.", minutes: 15, focusCategories: ["movement"], aimAssistFocus: null, items: [ { drillSlug: "camera_separation", minutes: 4, note: null }, { drillSlug: "vault_chain", minutes: 4, note: null }, { drillSlug: "cover_route", minutes: 7, note: null } ] },
  { slug: "close_30", name: "30-minute close-range block", description: "Jiggle, hip fire, and entries for hot drops and Arena.", minutes: 30, focusCategories: ["close_range", "aim"], aimAssistFocus: null, items: [ { drillSlug: "jiggle_basics", minutes: 5, note: null }, { drillSlug: "hipfire_circle", minutes: 5, note: null }, { drillSlug: "moving_spray", minutes: 6, note: null }, { drillSlug: "room_entry_pairs", minutes: 7, note: null }, { drillSlug: "jiggle_peek_duel", minutes: 7, note: null } ] },
  { slug: "dmr_30", name: "30-minute DMR clinic", description: "Cadence, micro-adjust, and moving leads.", minutes: 30, focusCategories: ["long_range"], aimAssistFocus: null, items: [ { drillSlug: "burst_grouping", minutes: 6, note: "Warm the reset" }, { drillSlug: "dmr_cadence_100", minutes: 8, note: null }, { drillSlug: "bolt_micro_adjust", minutes: 8, note: null }, { drillSlug: "moving_target_lead", minutes: 8, note: null } ] },
  { slug: "ur_prep_45", name: "45-minute Ultimate Royale prep", description: "The aim-assist-off program: manual tracking, switches, discipline (spec §5.6 readiness).", minutes: 45, focusCategories: ["aim", "recoil", "mid_range"], aimAssistFocus: "off", items: [ { drillSlug: "strafe_tracking_aa_off", minutes: 8, note: "Log vs your AA-on rate" }, { drillSlug: "target_switch_aa_off", minutes: 8, note: null }, { drillSlug: "first_ten_3x", minutes: 7, note: null }, { drillSlug: "full_mag_3x", minutes: 8, note: null }, { drillSlug: "peek_timer", minutes: 14, note: "Ranked-pace engagements" } ] },
  { slug: "utility_15", name: "15-minute utility block", description: "Frags, cooks, and smoke walls.", minutes: 15, focusCategories: ["throwables"], aimAssistFocus: null, items: [ { drillSlug: "frag_cook_windows", minutes: 5, note: null }, { drillSlug: "smoke_walls", minutes: 6, note: null }, { drillSlug: "bank_throws", minutes: 4, note: null } ] },
  { slug: "full_60", name: "60-minute full session", description: "The complete daily: aim, recoil, movement, game sense.", minutes: 60, focusCategories: ["aim", "recoil", "movement", "br_intelligence"], aimAssistFocus: "mixed", items: [ { drillSlug: "ads_transition_speed", minutes: 4, note: null }, { drillSlug: "strafe_tracking_aa_on", minutes: 6, note: null }, { drillSlug: "first_ten_3x", minutes: 6, note: null }, { drillSlug: "full_mag_3x", minutes: 7, note: null }, { drillSlug: "spray_transfer_pairs", minutes: 7, note: null }, { drillSlug: "cover_route", minutes: 6, note: null }, { drillSlug: "frag_cook_windows", minutes: 4, note: null }, { drillSlug: "rotation_timer", minutes: 20, note: "One deliberate casual match" } ] },
];

export const WOW_MAPS: WowMapRecord[] = [
  { slug: "sample-aim-arena", name: "Aim Arena (directory placeholder)", creatorLabel: null, mapCode: null, category: "aim", playerCount: "1", rules: "Static and strafing bots at 10–50m.", },
  { slug: "sample-recoil-range", name: "Recoil Range (directory placeholder)", creatorLabel: null, mapCode: null, category: "recoil", playerCount: "1", rules: "Wall targets at 20/35/50m with magazine refills.", },
  { slug: "sample-track-gym", name: "Tracking Gym (directory placeholder)", creatorLabel: null, mapCode: null, category: "tracking", playerCount: "1", rules: "Constant-strafe bots with speed tiers.", },
  { slug: "sample-switch-yard", name: "Switch Yard (directory placeholder)", creatorLabel: null, mapCode: null, category: "target_switching", playerCount: "1-2", rules: "Timed 3-target arcs.", },
  { slug: "sample-duel-box", name: "Duel Box (directory placeholder)", creatorLabel: null, mapCode: null, category: "duels", playerCount: "2-8", rules: "Round-based 1v1 with loadout resets.", },
  { slug: "sample-movement-course", name: "Movement Course (directory placeholder)", creatorLabel: null, mapCode: null, category: "movement", playerCount: "1-4", rules: "Vault chains, drop timings, sprint lines.", },
];
