import type { WeaponRecord } from "../schemas";

/**
 * The spec §5.3 required weapon list for the 4.5/S31 baseline.
 *
 * Data rules applied:
 * - Structural facts only (class, ammo, availability category, fire modes) — all
 *   data_status='unverified' pending editorial verification.
 * - NO numeric stats (damage/RoF/velocity/magazines): those live in weapon_stats
 *   rows only when a verifiable value exists. None do yet.
 * - `components` are 0–100 EDITORIAL estimates feeding the explainable meta
 *   engine, labeled low-confidence everywhere they surface.
 * - Availability categories that shift between versions carry a note instead of
 *   a guess being presented as fact.
 */

const EDITORIAL = {
  confidence: "low" as const,
  dataStatus: "unverified" as const,
  sourceName: "ClutchLab editorial baseline (pending verification)",
  sourceUrl: null,
  sourceDate: "2026-07-21",
  changeNote: null,
  notes: null,
};

export const WEAPONS: WeaponRecord[] = [
  // --- Assault rifles ---
  {
    ...EDITORIAL,
    slug: "ace32",
    name: "ACE32",
    class: "ar",
    ammo: "762",
    availability: "ground_loot",
    fireModes: ["single", "auto"],
    description:
      "7.62 AR with strong sustained damage; 4.5 reportedly improved its firing animation and recoil control.",
    components: { closeRange: 74, midRange: 82, longRange: 62, easeOfUse: 68, recoilDifficulty: 55 },
    attachmentDependency: "medium",
    changeNote:
      "4.5: firing animation and recoil improved (claim C4, secondary source — retest saved profiles).",
  },
  {
    ...EDITORIAL,
    slug: "m416",
    name: "M416",
    class: "ar",
    ammo: "556",
    availability: "ground_loot",
    fireModes: ["single", "auto"],
    description:
      "The flexible 5.56 workhorse: forgiving recoil once kitted, strong at every practical range.",
    components: { closeRange: 78, midRange: 84, longRange: 66, easeOfUse: 80, recoilDifficulty: 42 },
    attachmentDependency: "high",
  },
  {
    ...EDITORIAL,
    slug: "aug",
    name: "AUG A3",
    class: "ar",
    ammo: "556",
    availability: "ground_loot",
    fireModes: ["single", "auto"],
    description:
      "Premium 5.56 AR with high velocity and smooth spray; historically airdrop-only, ground loot in recent versions.",
    components: { closeRange: 77, midRange: 85, longRange: 68, easeOfUse: 78, recoilDifficulty: 40 },
    attachmentDependency: "high",
    notes: "Availability category to confirm for 4.5.",
  },
  {
    ...EDITORIAL,
    slug: "m762",
    name: "Beryl M762",
    class: "ar",
    ammo: "762",
    availability: "ground_loot",
    fireModes: ["single", "burst", "auto"],
    description:
      "Highest practical DPS among ground ARs; punishing recoil that rewards dedicated control practice.",
    components: { closeRange: 86, midRange: 80, longRange: 55, easeOfUse: 52, recoilDifficulty: 82 },
    attachmentDependency: "high",
  },
  {
    ...EDITORIAL,
    slug: "akm",
    name: "AKM",
    class: "ar",
    ammo: "762",
    availability: "ground_loot",
    fireModes: ["single", "auto"],
    description: "Hard-hitting classic 7.62 AR; vertical-heavy recoil, great tap-fire damage.",
    components: { closeRange: 80, midRange: 72, longRange: 50, easeOfUse: 58, recoilDifficulty: 72 },
    attachmentDependency: "medium",
  },
  {
    ...EDITORIAL,
    slug: "scarl",
    name: "SCAR-L",
    class: "ar",
    ammo: "556",
    availability: "ground_loot",
    fireModes: ["single", "auto"],
    description: "Comfortable 5.56 AR: gentle spray, slightly lower ceiling than the M416.",
    components: { closeRange: 74, midRange: 78, longRange: 60, easeOfUse: 82, recoilDifficulty: 38 },
    attachmentDependency: "medium",
  },
  {
    ...EDITORIAL,
    slug: "groza",
    name: "Groza",
    class: "ar",
    ammo: "762",
    availability: "airdrop",
    fireModes: ["single", "auto"],
    description: "Airdrop bullpup AR with elite close-mid DPS; limited attachments (suppressor-ready).",
    components: { closeRange: 92, midRange: 84, longRange: 55, easeOfUse: 66, recoilDifficulty: 60 },
    attachmentDependency: "low",
  },
  // --- SMGs ---
  {
    ...EDITORIAL,
    slug: "ump45",
    name: "UMP45",
    class: "smg",
    ammo: "45acp",
    availability: "ground_loot",
    fireModes: ["single", "burst", "auto"],
    description: "The stable all-round SMG: low recoil, real mid-range reach for its class.",
    components: { closeRange: 82, midRange: 62, longRange: 30, easeOfUse: 84, recoilDifficulty: 30 },
    attachmentDependency: "medium",
    changeNote: "4.5 SMG-class mobility changes may apply (claim C5, class-level, unconfirmed per weapon).",
  },
  {
    ...EDITORIAL,
    slug: "vector",
    name: "Vector",
    class: "smg",
    ammo: "9mm",
    availability: "ground_loot",
    fireModes: ["single", "auto"],
    description:
      "Extreme fire rate shredder; demands the extended mag and hugs close range.",
    components: { closeRange: 90, midRange: 55, longRange: 20, easeOfUse: 62, recoilDifficulty: 45 },
    attachmentDependency: "high",
    changeNote: "4.5 SMG-class mobility changes may apply (claim C5).",
  },
  {
    ...EDITORIAL,
    slug: "uzi",
    name: "Micro UZI",
    class: "smg",
    ammo: "9mm",
    availability: "ground_loot",
    fireModes: ["single", "auto"],
    description: "Fastest TTK in phone-booth range; falls off sharply past a few meters.",
    components: { closeRange: 88, midRange: 40, longRange: 12, easeOfUse: 70, recoilDifficulty: 35 },
    attachmentDependency: "low",
    changeNote: "4.5 SMG-class mobility changes may apply (claim C5).",
  },
  {
    ...EDITORIAL,
    slug: "mp5k",
    name: "MP5K",
    class: "smg",
    ammo: "9mm",
    availability: "map_exclusive",
    fireModes: ["single", "burst", "auto"],
    description: "Vikendi-associated SMG: heavy attachment slots, very controllable spray.",
    components: { closeRange: 84, midRange: 58, longRange: 25, easeOfUse: 80, recoilDifficulty: 32 },
    attachmentDependency: "medium",
    notes: "Map availability to confirm for 4.5.",
    changeNote: "4.5 SMG-class mobility changes may apply (claim C5).",
  },
  {
    ...EDITORIAL,
    slug: "p90",
    name: "P90",
    class: "smg",
    ammo: "other",
    availability: "map_exclusive",
    fireModes: ["single", "burst", "auto"],
    description: "50-round bullpup SMG seen in select modes/maps; sustained close-range pressure.",
    components: { closeRange: 89, midRange: 60, longRange: 22, easeOfUse: 72, recoilDifficulty: 38 },
    attachmentDependency: "low",
    notes: "Mode/map availability to confirm for 4.5.",
    changeNote: "4.5 SMG-class mobility changes may apply (claim C5).",
  },
  // --- Shotguns ---
  {
    ...EDITORIAL,
    slug: "dbs",
    name: "DBS",
    class: "shotgun",
    ammo: "12gauge",
    availability: "airdrop",
    fireModes: ["pump"],
    description: "Double-barrel bullpup shotgun: 14-shell pressure and brutal door fights.",
    components: { closeRange: 93, midRange: 35, longRange: 8, easeOfUse: 60, recoilDifficulty: 45 },
    attachmentDependency: "low",
    notes: "Airdrop vs ground availability to confirm for 4.5.",
  },
  {
    ...EDITORIAL,
    slug: "m1014",
    name: "M1014",
    class: "shotgun",
    ammo: "12gauge",
    availability: "ground_loot",
    fireModes: ["semi"],
    description: "Semi-auto shotgun with fast follow-ups; the standard ground-loot breacher.",
    components: { closeRange: 90, midRange: 30, longRange: 6, easeOfUse: 66, recoilDifficulty: 40 },
    attachmentDependency: "low",
  },
  {
    ...EDITORIAL,
    slug: "s12k",
    name: "S12K",
    class: "shotgun",
    ammo: "12gauge",
    availability: "ground_loot",
    fireModes: ["semi"],
    description: "Magazine-fed semi-auto shotgun; takes AR muzzles and mags.",
    components: { closeRange: 87, midRange: 28, longRange: 5, easeOfUse: 62, recoilDifficulty: 48 },
    attachmentDependency: "medium",
  },
  // --- DMRs ---
  {
    ...EDITORIAL,
    slug: "mini14",
    name: "Mini14",
    class: "dmr",
    ammo: "556",
    availability: "ground_loot",
    fireModes: ["semi"],
    description: "Low-recoil 5.56 DMR: fast cadence, generous mag, beginner-friendly poke.",
    components: { closeRange: 45, midRange: 76, longRange: 84, easeOfUse: 78, recoilDifficulty: 35 },
    attachmentDependency: "medium",
  },
  {
    ...EDITORIAL,
    slug: "mk12",
    name: "Mk12",
    class: "dmr",
    ammo: "556",
    availability: "ground_loot",
    fireModes: ["single", "semi"],
    description: "5.56 DMR with high velocity and clean follow-up shots.",
    components: { closeRange: 48, midRange: 78, longRange: 85, easeOfUse: 72, recoilDifficulty: 40 },
    attachmentDependency: "medium",
  },
  {
    ...EDITORIAL,
    slug: "slr",
    name: "SLR",
    class: "dmr",
    ammo: "762",
    availability: "ground_loot",
    fireModes: ["semi"],
    description: "Hard-hitting 7.62 DMR; heavy recoil rewards stock+grip and deliberate cadence.",
    components: { closeRange: 42, midRange: 80, longRange: 88, easeOfUse: 55, recoilDifficulty: 70 },
    attachmentDependency: "high",
  },
  {
    ...EDITORIAL,
    slug: "sks",
    name: "SKS",
    class: "dmr",
    ammo: "762",
    availability: "ground_loot",
    fireModes: ["semi"],
    description: "Attachment-hungry 7.62 DMR between the Mini14 and SLR in feel.",
    components: { closeRange: 40, midRange: 74, longRange: 82, easeOfUse: 58, recoilDifficulty: 62 },
    attachmentDependency: "high",
  },
  // --- Sniper rifles ---
  {
    ...EDITORIAL,
    slug: "awm",
    name: "AWM",
    class: "sr",
    ammo: "300magnum",
    availability: "airdrop",
    fireModes: ["bolt"],
    description: "The airdrop king: the only rifle that drops a level-3 helmet in one shot.",
    components: { closeRange: 30, midRange: 72, longRange: 98, easeOfUse: 45, recoilDifficulty: 55 },
    attachmentDependency: "medium",
  },
  {
    ...EDITORIAL,
    slug: "amr",
    name: "Lynx AMR",
    class: "sr",
    ammo: "300magnum",
    availability: "airdrop",
    fireModes: ["bolt"],
    description: "Anti-materiel airdrop rifle: extreme damage, shreds vehicles.",
    components: { closeRange: 26, midRange: 70, longRange: 97, easeOfUse: 40, recoilDifficulty: 60 },
    attachmentDependency: "medium",
    notes: "Availability in 4.5 to confirm.",
  },
  {
    ...EDITORIAL,
    slug: "m24",
    name: "M24",
    class: "sr",
    ammo: "762",
    availability: "ground_loot",
    fireModes: ["bolt"],
    description: "Ground-loot bolt action a tier above the Kar98k in power and handling.",
    components: { closeRange: 28, midRange: 68, longRange: 92, easeOfUse: 50, recoilDifficulty: 50 },
    attachmentDependency: "medium",
  },
  {
    ...EDITORIAL,
    slug: "kar98k",
    name: "Kar98k",
    class: "sr",
    ammo: "762",
    availability: "ground_loot",
    fireModes: ["bolt"],
    description: "The classic headshot lottery: iconic, available everywhere, unforgiving cadence.",
    components: { closeRange: 25, midRange: 64, longRange: 88, easeOfUse: 48, recoilDifficulty: 48 },
    attachmentDependency: "medium",
  },
  // --- LMGs ---
  {
    ...EDITORIAL,
    slug: "mg3",
    name: "MG3",
    class: "lmg",
    ammo: "762",
    availability: "airdrop",
    fireModes: ["auto"],
    description: "Airdrop LMG with selectable fire rates, bipod prone laser, vehicle deletion.",
    components: { closeRange: 78, midRange: 82, longRange: 60, easeOfUse: 55, recoilDifficulty: 68 },
    attachmentDependency: "low",
  },
  {
    ...EDITORIAL,
    slug: "dp28",
    name: "DP-28",
    class: "lmg",
    ammo: "762",
    availability: "ground_loot",
    fireModes: ["auto"],
    description: "47-round ground LMG: slow, heavy-hitting, shockingly stable when prone.",
    components: { closeRange: 66, midRange: 74, longRange: 52, easeOfUse: 64, recoilDifficulty: 52 },
    attachmentDependency: "low",
  },
  // --- Map-exclusive marker entry (spec list ends with "Map-exclusive weapons") ---
  {
    ...EDITORIAL,
    slug: "p90_note",
    name: "Map-exclusive pool (tracked)",
    class: "other",
    ammo: "other",
    availability: "map_exclusive",
    fireModes: [],
    description:
      "Placeholder tracking entry: additional map-exclusive weapons for 4.5 are pending verification before being cataloged individually.",
    components: { closeRange: 0, midRange: 0, longRange: 0, easeOfUse: 0, recoilDifficulty: 50 },
    attachmentDependency: "low",
    dataStatus: "sample",
    notes: "Not a real weapon — excluded from tier seeding.",
  },
];

/** Weapons included in tier snapshots (excludes tracking placeholders). */
export const TIERABLE_WEAPONS = WEAPONS.filter((w) => w.dataStatus !== "sample");
